name: Check by compiler_jikken command

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Run compiler_jikken command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0

      - name: Run check
        id: check
        run: eval $(opam env) && compiler_jikken --debug --ci 0 --toi 99
        continue-on-error: true

      - run: exit 1
        if: steps.check.outcome == 'failure'
