name: Check by compiler_jikken command

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Run compiler_jikken command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0

      - name: Install compiler_jikken command
        run: opam pin add -y compiler_jikken https://github.com/s-ylide/compiler_jikken.git#feat/ci-mode

      - name: Debug dune
        run: git ls-files dune **/dune
      - name: Debug Rust
        run: git ls-files Cargo.toml **/Cargo.toml
      - name: Run check
        run: eval $(opam env) && compiler_jikken --debug --ci 4 --toi 2 --toi 3
        continue-on-error: true
      - name: Debug Artifacts
        run: ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: check-artifact
          path: artifact/
